Add support for additional watch directories
anomalyco/sst pull request #5074
Opened 2024-11-15 18:39 UTC by nirweiner2

2024-11-17 08:44 UTC, noaklein57 approved these changes

2024-11-20 22:27 UTC, nirweiner2 commented
Hi @thdxr  and team, 👋

I wanted to kindly follow up on this pull request.
I’d really appreciate any feedback or suggestions whenever you have a moment.
Thank you for your time and support! 🙏

Nir

2024-12-03 17:54 UTC, nirweiner2 commented
Hi guys.
I've solved the conflicts in this commit.
Would really love to have some feedback on this one.

2024-12-06 22:48 UTC, jayair commented
Sorry haven't had a chance to get to this. We are going to look at it in the coming weeks.

2024-12-28 20:47 UTC, nirweiner2 commented
Hi @jayair, @thdxr.

I’d really appreciate any feedback or suggestions to help get this PR merged.
From #2618, it seems like many teams could benefit from this. If it’s not something you’re planning to move forward with, that’s also helpful information, as it will guide me in exploring other solutions.

Thank you for your time and input!

2025-01-04 00:14 UTC, jayair commented
@thdxr let's take a look?

2025-01-10 17:33 UTC, san4d commented
I'm interested in this change as well. Thanks for putting it together and for the team for reviewing.

For reference, here's a rough layout of my monorepo:
```text
.
├── deployments
│   ├── core
│   │   ├── apps
│   │   │   ├── app-a
│   │   │   └── app-b
│   │   ├── functions
│   │   │   ├── fn-a
│   │   │   ├── fn-b
│   │   │   └── fn-c
│   │   ├── package.json
│   │   ├── sst-env.d.ts
│   │   └── sst.config.ts
│   ├── marketing
│   │   ├── package.json
│   │   ├── sst-env.d.ts
│   │   └── sst.config.ts
│   └── org
│   │   ├── package.json
│   │   ├── sst-env.d.ts
│   │   └── sst.config.ts
├── modules
│   ├── adapters
│   ├── domains
│   └── flows
├── package.json
├── packages
│   ├── lib-a
│   ├── lib-b
│   └── lib-c
├── pnpm-lock.yaml
└── pnpm-workspace.yaml
```
The directories under deployments are isolated namespaces that help contain the impact of infra changes. The business logic mainly comes from the modules subdirectories, which are reused across deployments.

This MR appears to reload at the root of the sst project. While this is a good improvement, ideally I'd be able to specify which files/directories to watch at a resource level. For example, the functions in my repo (ex. `fn-a`) are very small and do not have many dependencies, so they don't need to reload as often as the apps.

2025-01-22 20:32 UTC, arvind-iyer-dev commented
This PR is a great feature add, but the issue is that only .js / .ts files are diffed in this process.
I'm trying to use AppSync with this.
And the watcher doesn't seem to look through Graphql Files.
Would be great if we could support more file extensions like
`.graphql` or `prisma.schema`

2025-02-09 08:49 UTC, nirweiner2 commented
Hey guys,
I've resolved the conflicts in this PR and would appreciate it if we could move forward with merging it.

2025-02-26 16:45 UTC, nirweiner2 commented
Hello @thdxr, @jayair,

I would be grateful for any feedback you may have regarding this PR, which has been open since November. My team and I are becoming concerned about its progress, and we would greatly appreciate any insights into whether there might be an opportunity for it to be merged. If not, kindly advise so that we may consider alternative solutions.

We also have several other contributions we are enthusiastic about sharing with the project, and your guidance would be immensely helpful.

Thank you very much for your time and consideration.

2025-03-01 00:14 UTC, jayair commented
Yeah sorry we haven't had a chance to look into this because it's bit of a bigger change on our end and this hasn't been a priority.

2025-07-18 02:43 UTC, nirweiner2 commented
@jayair @thdxr
Hi guys. bumping it again maybe someone can find the time to look into it.
Thank you.

2025-08-18 09:52 UTC, alexbeletsky commented
This is very important change that unblocks working with SST in big monorepos, which is currently [blocked](https://github.com/sst/sst/issues/4233#issuecomment-3195946334);

Upvoting it! @jayair @thdxr

2025-09-17 15:14 UTC, nirweiner2 commented
Maybe this time?

2025-10-27 08:48 UTC, nirweiner2 commented
Hey @jayair , @thdxr.
Would love your thoughts on this — it’s something the community really needs, and I’m more than happy to make any changes required to get it merged.
Thanks a lot!

2025-12-05 14:38 UTC, jamesgibbons92 requested changes

2025-12-05 14:38 UTC, jamesgibbons92 commented on platform/src/config.ts
> +
The multi line comment below this is now malformed.

2025-12-05 20:56 UTC, fwang commented
@nirweiner2 catching up on this.. do u mind resolving the conflicts? I can merge after that.

2025-12-12 13:02 UTC, keypuncherlabs commented
I'm using a monorepo and would love to see this PR merged as well, thank you for doing this!

2026-01-04 11:46 UTC, nirweiner2 commented
This change closely mirrors https://github.com/anomalyco/sst/pull/5652
. Since that PR has already been merged, this one is no longer necessary. We waited for it to land until about two months ago, after which we decided to move forward with an alternative solution.

2026-01-04 11:46 UTC, closed without merging